apiVersion: apps/v1
kind: Deployment
metadata:
  name: artifact-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artifact
  template:
    metadata:
      labels:
        app: artifact
    spec:
      containers:
      - name: artifact-container
        image: rohit7mahi/cultural_artifact_app
        ports:
        - containerPort: 8501

---
apiVersion: v1
kind: Service
metadata:
  name: artifact-service
spec:
  type: NodePort
  selector:
    app: artifact
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
      nodePort: 30501
