name: Build and Deploy to K3s

on:
  push:
    branches:
      - main  # Adjust if using another default branch

env:
  IMAGE_NAME: rohit7mahi/cultural_artifact_app

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.IMAGE_NAME }}:${{ github.sha }}
          ${{ env.IMAGE_NAME }}:latest

  deploy:
    name: Deploy to K3s
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > kubeconfig
        export KUBECONFIG=$PWD/kubeconfig

    - name: Set image in K3s deployment
      run: |
        export KUBECONFIG=$PWD/kubeconfig
        kubectl set image deployment/cultural-artifact-app cultural-artifact-app=${{ env.IMAGE_NAME }}:${{ github.sha }}
