name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu environment.

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checks out the code in the repository.

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1  # Set up Docker Buildx for building multi-platform images.

      - name: Log in to Docker Hub
        uses: docker/login-action@v2  # Log in to Docker Hub using GitHub Secrets.
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username (set as GitHub Secret).
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password or token (set as GitHub Secret).

      - name: Build Docker image
        run: |
          docker build -t rohit7mahi/cultural_artifact_app:$GITHUB_SHA .  # Build Docker image with commit SHA as the tag.

      - name: Push Docker image to Docker Hub
        run: |
          docker push rohit7mahi/cultural_artifact_app:$GITHUB_SHA  # Push the image to Docker Hub.

  deploy:
    runs-on: ubuntu-latest  # Runs the deploy job on an Ubuntu machine.
    needs: build  # Ensure the build job is complete before running this.

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checks out the code again for deployment.

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1  # Set up kubectl to interact with Kubernetes.

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/cultural-artifact-app cultural-artifact-app=rohit7mahi/cultural_artifact_app:$GITHUB_SHA  # Update the image in Kubernetes deployment.
          kubectl rollout status deployment/cultural-artifact-app  # Wait until the deployment completes successfully.
